### ISSUE TITLE
Simple change to make toisto work on Linux/windows

### ISSUE THREAD

**Issue by Haiz14** [fniessink/toisto#176]
The only MacOs dependency is `say` and `afplay`.
There are equivalent (lots of) for them Linux and Windows.

We could use a config file file that where we can set the command which does the same thing on that OS
For eg on macos
```text
audio-play-command: "say"
x-command: "afplay" # idk what afplay does
```

p.s. i think very few users will use the audio commands, most woul just use text based learning.

**Comment by fniessink** [comment]
I'll look into it. Would be great if you're willing to test it because I don't have access to a Windows or Linux machine at the moment.

**Comment by Haiz14** [comment]
I have a Linux machine, but can you tell me which files you have specified those 2 commamds

**Comment by fniessink** [comment]
It's currently in [`src/toisto/ui/speech.py`](https://github.com/fniessink/toisto/blob/main/src/toisto/ui/speech.py).

**Comment by fniessink** [comment]
I have a [PR](#178) open. Waiting for my son to return home with his Windows laptop so I can test it on Windows.
