### ISSUE TITLE
basic commands result in an error on Windows

### ISSUE THREAD

**Issue by Sebastiaan127001** [fniessink/toisto#221]
I have created a config file in the home directory as described in the help page.

I ran the command 
>toisto topics --topic nature
And this resulted in an error.

![image](https://user-images.githubusercontent.com/95095453/219781086-8a899c34-7980-4839-a081-ab83fb18dbf6.png)

I ran this on a Windows machine.

the command toisto practice also results in an error.

![image](https://user-images.githubusercontent.com/95095453/219782004-132870e6-7a21-4fc4-af1b-b8f3613b8976.png)

The config file is in the same dir as the progress file, the home dir

![image](https://user-images.githubusercontent.com/95095453/219782627-ef3c80f7-6d24-4fd8-9c67-379c7ad752af.png)

![image](https://user-images.githubusercontent.com/95095453/219783059-dfeb3d6c-f344-426b-89bd-1429f26fe74b.png)

**Comment by fniessink** [comment]
Sections can't be repeated in the config file, see https://github.com/fniessink/toisto#how-to-configure-your-language-level. 

The file should read:

```ini
[languages]
target = nl
source = en
levels = A1 A2 B1
```

Nevertheless, Toisto shouldn't crash on an invalid config file, so I'll try to fix that.
