### ISSUE TITLE
Sienestä and käydä sienessä appear to be different words in Toisto

### ISSUE THREAD

**Issue by DerAlfa** [fniessink/toisto#919]
There are two ways of saying to pick mushrooms.
I would expect both versions would be correct when Toisto asks to translate but it seems they're considered different words.
My suggestion is to connect them as synonyms for eachother.

Check the bottom of my screenshot for reference.

![paddenstoelen_plukken](https://github.com/user-attachments/assets/0540578c-7b24-4278-b50a-cd2c8bc4a2f4)

**Comment by fniessink** [comment]
Agreed. The same goes for:
- vissen/kalastaa/käydä kalassa
- bessen plukken/marjastaa/käydä marjassa

**Comment by fniessink** [comment]
Should be fixed in version 0.31.0 (to be released in a few minutes).
